# Generated by Django 4.2.1 on 2023-06-15 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('empleados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargos',
            fields=[
                ('IDencargo', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_encargo', models.DateTimeField(auto_now_add=True)),
                ('Fecha_entrega', models.DateTimeField()),
                ('Anticipo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IDcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Recibio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('IDfactura', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('Total_a_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IDcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Info_facturas',
            fields=[
                ('IDinfo_factura', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('IDfactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.facturas')),
                ('IDproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Info_encargos',
            fields=[
                ('IDinfo_encargos', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
                ('IDencargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.encargos')),
                ('IDproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes_facturas',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('IDcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('IDfactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.facturas')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes_encargos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('IDcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('IDencargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.encargos')),
            ],
        ),
    ]
