# Generated by Django 4.2.1 on 2023-06-26 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargos',
            name='Recibio',
        ),
    ]
