# Generated by Django 4.2.1 on 2023-07-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_encargos_anticipo_alter_encargos_total_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientes_encargos',
            table='Clientes_encargos',
        ),
        migrations.AlterModelTable(
            name='clientes_facturas',
            table='Clientes_facturas',
        ),
        migrations.AlterModelTable(
            name='encargos',
            table='Encargos',
        ),
        migrations.AlterModelTable(
            name='facturas',
            table='Facturas',
        ),
        migrations.AlterModelTable(
            name='info_encargos',
            table='Info_encargos',
        ),
        migrations.AlterModelTable(
            name='info_facturas',
            table='Info_facturas',
        ),
    ]
