# Generated by Django 4.2.3 on 2023-07-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_clientes_encargos_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
