# Generated by Django 4.2.1 on 2023-07-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_facturas_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargos',
            name='Fecha_entrega',
            field=models.DateField(),
        ),
    ]
