# Generated by Django 4.2.3 on 2023-08-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_encargos_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargos',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
