# Generated by Django 4.2.1 on 2023-08-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_encargos_fecha_encargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargos',
            name='Total_comision',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='Total_comision',
        ),
    ]
