# Generated by Django 4.2.1 on 2023-06-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='Correo',
            field=models.EmailField(default='mares@gmail.com', max_length=254, unique=True),
        ),
    ]
