# Generated by Django 4.2.1 on 2023-06-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleados_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='Horario',
        ),
        migrations.AddField(
            model_name='empleados',
            name='Horario_fin',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='Horario_inicio',
            field=models.TimeField(default='00:00'),
        ),
    ]
