# Generated by Django 4.2.1 on 2023-07-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_remove_empleados_horario_empleados_horario_fin_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empleados',
            table='Empleados',
        ),
    ]
