# Generated by Django 4.2.1 on 2023-07-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_empleados_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='Correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
