# Generated by Django 4.2.1 on 2023-06-15 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('IDcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('IDproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('Descripcion', models.TextField()),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Imagen', models.URLField()),
                ('IDcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categorias')),
            ],
        ),
    ]
