# Generated by Django 4.2.1 on 2023-06-16 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
