# Generated by Django 4.2.1 on 2023-07-11 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0002_rename_nombre_productos_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opiniones',
            fields=[
                ('IDopinion', models.AutoField(primary_key=True, serialize=False)),
                ('Opinion', models.CharField(max_length=255)),
                ('IDproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
