# Generated by Django 4.2.1 on 2023-07-12 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_opiniones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opiniones',
            name='Usuario',
        ),
    ]
