# Generated by Django 4.2.1 on 2023-07-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_opiniones_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
