# Generated by Django 4.2.1 on 2023-07-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_categorias_activa_productos_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='activa',
        ),
    ]
